const { fetchNotionData, updateNotionPage, logBotAction } = require('./notion_llm');
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const AI_TOOLS = [
  {
    functionDeclarations: [
      {
        name: "getNotionSprints",
        description: "Fetch current active tasks from the Notion Sprint Board for a specific role or all.",
        parameters: {
          type: "OBJECT",
          properties: {
            role: { type: "STRING", description: "Role name (e.g. taras, mykyta, nazar, all)" },
            status: { type: "STRING", description: "Filter by status (e.g. 'To Do', 'In Progress', 'Done', 'Blocked')" }
          }
        }
      },
      {
        name: "updateTaskStatusSync",
        description: "Updates the status of a specific task in Notion Sprint Board AND synchronizes it to the local PostgreSQL database.",
        parameters: {
          type: "OBJECT",
          properties: {
            notionPageId: { type: "STRING", description: "The ID of the Notion page (from getNotionSprints)." },
            taskText: { type: "STRING", description: "The exact text name of the task to find it in the Prisma DB." },
            newStatus: { type: "STRING", description: "One of: 'To Do', 'In Progress', 'Done', 'Blocked'" }
          },
          required: ["notionPageId", "taskText", "newStatus"]
        }
      },
      {
        name: "getOperationsPipeline",
        description: "Fetch contacts and status from the Operations Center DB (suppliers, legal, logistics, printing).",
        parameters: {
          type: "OBJECT",
          properties: {
            area: { type: "STRING", description: "Optional filter by Area (e.g. Сировина, Тара, Пакування)." },
            status: { type: "STRING", description: "Optional filter by Status (e.g. 'Новий', 'В роботі')." }
          }
        }
      },
      {
        name: "getLegalDocs",
        description: "Fetch legal documents and their current status from the Notion Legal DB. Useful for TM registration, HACCP, certifications, contracts.",
        parameters: {
          type: "OBJECT",
          properties: {
            status: { type: "STRING", description: "Optional: filter by status, e.g. 'В процесі', 'Готово', 'Потрібна дія'." },
            docType: { type: "STRING", description: "Optional: document type like 'ТМ', 'ХАСП', 'Договір'." }
          }
        }
      },
      {
        name: "getB2BPartners",
        description: "Fetch B2B partners, leads and potential clients from the Notion B2B database.",
        parameters: {
          type: "OBJECT",
          properties: {
            status: { type: "STRING", description: "Optional filter by deal status." },
            category: { type: "STRING", description: "Optional category filter (e.g. Horeca, Retail, Corporate)." }
          }
        }
      },
      {
        name: "getInfluencers",
        description: "Fetch blogger/influencer records from Notion Influencer DB — shipping status, niche, followers.",
        parameters: {
          type: "OBJECT",
          properties: {
            status: { type: "STRING", description: "Optional filter: 'Надіслано', 'Відгук є', 'В роботі'." }
          }
        }
      },
      {
        name: "getAcademyProgress",
        description: "Fetch all training modules and their completion status from the Notion Academy database.",
        parameters: {
          type: "OBJECT",
          properties: {
            role: { type: "STRING", description: "Optional: filter by role (Тарас, Микита, Назар)." },
            status: { type: "STRING", description: "Optional: filter by completion status." }
          }
        }
      },
      {
        name: "logAgentInsight",
        description: "Write a summary or important insight generated by you (the AI) directly into the Notion Bot Log for the team to see.",
        parameters: {
          type: "OBJECT",
          properties: {
            title: { type: "STRING", description: "Short summary title of the insight." },
            details: { type: "STRING", description: "Detailed description of the insight, warning, or observation." },
            member: { type: "STRING", description: "The member this insight relates to, or 'System'." }
          },
          required: ["title", "details"]
        }
      }
    ]
  }
];


async function handleFunctionCall(functionCall) {
  const { name, args } = functionCall;
  const argsObj = args; // depending on SDK version could be args or args.fields 

  console.log(`🧠 [AI TOOL EXEC] ${name}() called by Gemini`);

  if (name === "getNotionSprints") {
    let filter = undefined;
    const filterConditions = [];
    
    // Map internal roles to Notion Select options
    const teamMap = { 'taras': 'Тарас', 'mykyta': 'Микита', 'nazar': 'Назар' };
    
    if (argsObj.role && argsObj.role !== 'all') {
      const notionRole = teamMap[argsObj.role.toLowerCase()] || argsObj.role;
      filterConditions.push({ property: 'Owner', select: { equals: notionRole } });
    }
    if (argsObj.status) {
      filterConditions.push({ property: 'Status', status: { equals: argsObj.status } });
    }

    if (filterConditions.length > 1) {
      filter = { and: filterConditions };
    } else if (filterConditions.length === 1) {
      filter = filterConditions[0];
    }
    
    const data = await fetchNotionData('TASKS', filter);
    return { tasks: data };
  }

  if (name === "updateTaskStatusSync") {
    const { notionPageId, taskText, newStatus } = argsObj;
    
    // 1. Update Notion
    await updateNotionPage(notionPageId, {
      'Status': { status: { name: newStatus } }
    });

    // 2. Synchronize to Prisma (PostgreSQL / SQLite)
    const isDone = newStatus.toLowerCase() === 'done';
    
    // Find task in Prisma DB using text matching (Since Notion doesn't have Prisma ID stored)
    const existingPrismaTask = await prisma.task.findFirst({
      where: { text: { contains: taskText.substring(0, 30) } }, // Fuzzy match
      orderBy: { id: 'desc' }
    });

    if (existingPrismaTask) {
      await prisma.task.update({
        where: { id: existingPrismaTask.id },
        data: { done: isDone, completedAt: isDone ? new Date() : null }
      });
      return { success: true, message: `Updated Notion and Prisma Task (${existingPrismaTask.id}) to ${newStatus}` };
    }
    
    return { success: true, message: `Updated Notion. Did NOT find matching task in Prisma to sync.` };
  }

  if (name === "getOperationsPipeline") {
    let filter = undefined;
    const conds = [];
    if (argsObj.area) conds.push({ property: 'Area', select: { equals: argsObj.area } });
    if (argsObj.status) conds.push({ property: 'Status', select: { equals: argsObj.status } });
    
    if (conds.length > 1) filter = { and: conds };
    else if (conds.length === 1) filter = conds[0];

    const data = await fetchNotionData('OPS', filter);
    return { records: data };
  }

  if (name === "getLegalDocs") {
    const conds = [];
    if (argsObj.status) conds.push({ property: 'Status', select: { equals: argsObj.status } });
    if (argsObj.docType) conds.push({ property: 'Type', select: { equals: argsObj.docType } });
    const filter = conds.length > 1 ? { and: conds } : conds[0] || undefined;
    const data = await fetchNotionData('LEGAL', filter);
    return { docs: data };
  }

  if (name === "getB2BPartners") {
    const conds = [];
    if (argsObj.status)   conds.push({ property: 'Status', select: { equals: argsObj.status } });
    if (argsObj.category) conds.push({ property: 'Category', select: { equals: argsObj.category } });
    const filter = conds.length > 1 ? { and: conds } : conds[0] || undefined;
    const data = await fetchNotionData('B2B', filter);
    return { partners: data };
  }

  if (name === "getInfluencers") {
    const filter = argsObj.status
      ? { property: 'Status', select: { equals: argsObj.status } }
      : undefined;
    const data = await fetchNotionData('INFLUENCER', filter);
    return { influencers: data };
  }

  if (name === "getAcademyProgress") {
    const conds = [];
    const teamMap = { 'taras': 'Тарас', 'mykyta': 'Микита', 'nazar': 'Назар' };
    if (argsObj.role) {
      const notionRole = teamMap[argsObj.role.toLowerCase()] || argsObj.role;
      conds.push({ property: 'Assigned To', select: { equals: notionRole } });
    }
    if (argsObj.status) conds.push({ property: 'Status', select: { equals: argsObj.status } });
    const filter = conds.length > 1 ? { and: conds } : conds[0] || undefined;
    const data = await fetchNotionData('ACADEMY', filter);
    return { modules: data };
  }

  if (name === "logAgentInsight") {
    await logBotAction(argsObj.title, argsObj.details, argsObj.member || 'System');
    return { success: true, message: "Logged to Notion successfully." };
  }

  return { error: `Unknown function ${name}` };
}


module.exports = {
  AI_TOOLS,
  handleFunctionCall
};
